let REVIEW_LANG=localStorage.getItem('am_lang')||'en';
const COPY={
 en:{record:'Attempt record',next:'Coach’s next move',problems:'Problems',map:'Problem map',review:'Problem review',correct:'Correct',wrong:'Wrong',blank:'Blank',before:'Review attempt',answerLabel:'Your answer',submitAnswer:'Submit answer',markBlank:'Leave blank',giveUp:'Give up',timer:'Working time',mapFirst:'Map before hints',mapHelp:'Choose at least two concepts, choose a first representation, and explain why it fits.',representation:'First representation',reason:'Why does it fit?',saveMap:'Save map · unlock Hint 1',mapNeed:'Choose two concepts, a representation, and write at least 12 characters.',mapSaved:'Map saved. Hint 1 is unlocked.',hint:'Hint',solution:'Worked solution',openSolution:'Open solution · complete review stage',practice:'Transfer practice',check:'Check independently',reviewed:'Review complete',transfer:'Transfer passed',cold:'48-hour cold redo',locked:'Locked',ready:'Ready',passed:'Passed',progress:'evidence stages completed',notYet:'Complete the previous stage first.',wait48:'Available 48 hours after transfer passes.',coldStart:'Start cold redo',coldSubmit:'Submit cold redo',statusCorrect:'Correct',statusWrong:'Not correct yet',statusBlank:'Recorded blank',statusGiveup:'Recorded as give up',tryAgain:'Try the original again before opening help.',independent:'No hints and no answer reveal. One correct transfer is required.',coldRule:'Original problem, no notes, no hints. The timer restarts.',stageReview:'Submit → map → study solution',stageTransfer:'Solve one variation independently',stageCold:'Return after 48 hours; solve cold',sourceBlank:'Blank on the archived attempt',answerAfterPass:'Answer shown because transfer is already passed.',whyMap:'The launch matters more than the calculation.'},
 zh:{record:'本次记录',next:'教练下一步',problems:'题目',map:'题目地图',review:'逐题复盘',correct:'正确',wrong:'错误',blank:'空白',before:'本次复盘作答',answerLabel:'你的答案',submitAnswer:'提交答案',markBlank:'留空',giveUp:'放弃本题',timer:'本题用时',mapFirst:'看提示前先映射',mapHelp:'至少选择两个知识点，选择第一种表示，并说明它为什么适合。',representation:'第一种表示',reason:'为什么适合？',saveMap:'保存映射 · 解锁提示1',mapNeed:'请选择两个知识点、一种表示，并写至少12个字。',mapSaved:'映射已保存。提示1已解锁。',hint:'提示',solution:'完整解析',openSolution:'打开解析 · 完成复盘阶段',practice:'迁移训练',check:'独立检查',reviewed:'复盘完成',transfer:'迁移通过',cold:'48小时冷重做',locked:'未解锁',ready:'可进行',passed:'已通过',progress:'项学习证据阶段已完成',notYet:'请先完成上一阶段。',wait48:'迁移通过48小时后开放。',coldStart:'开始冷重做',coldSubmit:'提交冷重做',statusCorrect:'回答正确',statusWrong:'暂未答对',statusBlank:'已记录为空白',statusGiveup:'已记录为放弃',tryAgain:'打开帮助前，再试一次原题。',independent:'不看提示、不看答案；独立做对一道迁移题才算通过。',coldRule:'原题、无笔记、无提示；计时重新开始。',stageReview:'提交 → 映射 → 学习解析',stageTransfer:'独立做对一道变式',stageCold:'48小时后无提示重做',sourceBlank:'历史作答为空白',answerAfterPass:'因迁移已通过，现显示答案。',whyMap:'启动方式比计算过程更重要。'}
};
const C=()=>COPY[REVIEW_LANG];
const L=x=>typeof x==='string'?x:(x?.[REVIEW_LANG]??x?.en??x?.zh??'');
const mono=x=>({en:x});
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const optionList=x=>Object.entries(x||{}).map(([key,text])=>({key,text:String(text)}));
const representations=[['equation','Equation or system','方程或方程组'],['cases','Cases or complement','分类或补集'],['coordinates','Coordinates or diagram','坐标或图形'],['state','Recurrence or state','递推或状态'],['factors','Factors or divisibility','因数或整除'],['symmetry','Symmetry or invariant','对称或不变量']];
function normalize(x){return String(x??'').toLowerCase().replace(/sqrt\s*\(?\s*([0-9]+)\s*\)?/g,'√$1').replace(/[\\{}\s$()]/g,'').replace(/−/g,'-').replace(/·/g,'*')}
function isCorrect(input,p){const n=normalize(input);return [p.answer.choice,p.answer.value,...p.options.filter(o=>o.key===p.answer.choice).map(o=>o.text)].some(x=>normalize(x)===n)}
function formatTime(ms){const total=Math.max(0,Math.floor(ms/1000)),m=Math.floor(total/60),s=total%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function formatDate(x){if(!x)return 'Archive';try{return new Intl.DateTimeFormat(REVIEW_LANG==='zh'?'zh-CN':'en-US',{year:'numeric',month:'short',day:'numeric'}).format(new Date(`${x}T12:00:00`))}catch{return x}}
function renderMath(root=document){if(window.renderMathInElement)renderMathInElement(root,{delimiters:[{left:'$$',right:'$$',display:true},{left:'$',right:'$',display:false},{left:'\\(',right:'\\)',display:false},{left:'\\[',right:'\\]',display:true}],throwOnError:false})}
function adapt2011(raw){return{id:'2011-amc10a',meta:{year:2011,form:raw.meta.form,date:raw.meta.date,total:25},problems:raw.problems.map(p=>({number:p.num,title:null,topic:p.topic,stem:p.stem,options:optionList(p.options),answer:{choice:p.ans,value:p.ansValue},mapSummary:p.trap,concepts:p.tags.en.map((x,i)=>({id:`tag${i}`,label:{en:x,zh:p.tags.zh[i]}})),required:[],prompt:{en:'Which ideas and representation would you test first?',zh:'你会先尝试哪些知识点和表示？'},hints:p.hintChain.map((h,i)=>({id:`h${i}`,prompt:h.q,content:h.hint})),solutions:p.methods.map((m,i)=>({id:`m${i}`,title:mono(m.name),steps:m.steps.map(mono),result:m.result})),practice:p.similar.map((s,i)=>({id:`p${i}`,question:mono(s.q),answer:mono(s.answer),sketch:mono(s.sketch),level:s.level}))}))}}
function adapt2012(raw){return{id:'2012-amc10a',meta:{year:2012,form:'AMC 10A',date:'February 7, 2012',total:25,cutoff:raw.meta.cutoff},problems:raw.problems.map(p=>({number:p.num,title:p.title,topic:p.topic,stem:p.stem,options:optionList(p.options),answer:{choice:p.answer,value:p.value},mapSummary:p.map,concepts:p.concepts.map(c=>({id:c[0],label:{en:c[1],zh:c[2]}})),required:p.required,prompt:p.prompt,hints:p.hints.map((h,i)=>({id:`h${i}`,content:h})),solutions:[{id:'core',title:{en:'Core method',zh:'关键解法'},steps:p.solution.steps.en.map((s,i)=>({en:s,zh:p.solution.steps.zh[i]})),result:p.value,insight:p.solution.insight}],practice:[{id:'transfer',question:p.transfer.q,answer:p.transfer.a}]}))}}
const EXAM=window.EXAM_2011_10A?adapt2011(window.EXAM_2011_10A):adapt2012(window.EXAM_2012_10A);
const ATTEMPT=(window.REVIEW_ATTEMPTS||[]).find(a=>a.exam===`${EXAM.meta.year} ${EXAM.meta.form}`)||{};
const STATE_KEY=`review:${EXAM.id}:learning-v3`;
const SCORE_KEY=`review:${EXAM.id}:score-v1`;
let SCORE_STATE={};try{SCORE_STATE=JSON.parse(localStorage.getItem(SCORE_KEY)||'{}')||{}}catch{SCORE_STATE={}}
let STATE={};
try{STATE=JSON.parse(localStorage.getItem(STATE_KEY)||'{}')||{}}catch{STATE={}}
function defaults(){return{startedAt:null,elapsed:0,outcome:null,answer:'',map:null,hintsOpened:0,hintUsed:false,reviewedAt:null,transferPassedAt:null,transferIndex:0,transferAttempts:0,coldStartedAt:null,coldPassedAt:null,coldAnswer:'',coldElapsed:0}}
function ps(n){STATE[n]=Object.assign(defaults(),STATE[n]||{});return STATE[n]}
function save(){localStorage.setItem(STATE_KEY,JSON.stringify(STATE))}
function startTimer(n,kind='main'){const s=ps(n),key=`${n}:${kind}`;if(kind==='main'&&!s.startedAt){s.startedAt=Date.now();save()}if(kind==='cold'&&!s.coldStartedAt){s.coldStartedAt=Date.now();save()}if(timers[key])return;timers[key]=setInterval(()=>updateTimer(n,kind),1000);updateTimer(n,kind)}
function stopTimer(n,kind='main'){clearInterval(timers[`${n}:${kind}`]);delete timers[`${n}:${kind}`];updateTimer(n,kind)}
function timerValue(s,kind){if(kind==='cold')return s.coldElapsed+(s.coldStartedAt&&!s.coldPassedAt?Date.now()-s.coldStartedAt:0);return s.elapsed+(s.startedAt&&!s.outcome?Date.now()-s.startedAt:0)}
function updateTimer(n,kind='main'){const el=document.querySelector(`[data-timer="${n}:${kind}"]`);if(el)el.textContent=formatTime(timerValue(ps(n),kind))}
function freezeMain(s){if(s.startedAt&&!s.outcome){s.elapsed+=Date.now()-s.startedAt;s.startedAt=null}}
function setOutcome(n,outcome,answer=''){const p=EXAM.problems.find(x=>x.number===n),s=ps(n);freezeMain(s);s.answer=answer;s.outcome=outcome==='answer'?(isCorrect(answer,p)?'correct':'wrong'):outcome;save();stopTimer(n);render();requestAnimationFrame(()=>document.querySelector(`#problem-${n}`)?.setAttribute('open',''))}
function stageCount(s){return Number(!!s.reviewedAt)+Number(!!s.transferPassedAt)+Number(!!s.coldPassedAt)}
function coldReady(s){return !!s.transferPassedAt&&Date.now()-s.transferPassedAt>=48*60*60*1000}
function outcomeLabel(s){if(s.coldPassedAt)return C().passed;if(!s.outcome)return C().sourceBlank;return s.outcome==='correct'?C().statusCorrect:s.outcome==='wrong'?C().statusWrong:s.outcome==='giveup'?C().statusGiveup:C().statusBlank}
function summaryLabel(s){if(s.coldPassedAt)return C().passed;if(s.transferPassedAt)return C().transfer;if(s.reviewedAt)return C().reviewed;return outcomeLabel(s)}
let timers={};

function renderHeader(){document.documentElement.lang=REVIEW_LANG;document.title=`${EXAM.meta.year} ${EXAM.meta.form} · Suri’s Math`;document.getElementById('examDate').textContent=EXAM.meta.date||formatDate(ATTEMPT.attemptedAt);document.getElementById('examTitle').innerHTML=`${EXAM.meta.year}<br>${EXAM.meta.form}`;document.getElementById('examDiagnosis').textContent=`${REVIEW_LANG==='zh'?'本页只复盘':'This page reviews only'} ${ATTEMPT.sourceQuestions||EXAM.problems.map(p=>`Q${p.number}`).join(', ')} ${REVIEW_LANG==='zh'?'，来自完整25题试卷。':'from the full 25-question exam.'} ${L(ATTEMPT.diagnosis)}`;document.getElementById('recordTitle').textContent=C().record;document.getElementById('nextAction').textContent=L(ATTEMPT.nextAction);document.querySelector('.next span').textContent=C().next;document.getElementById('mapTitle').textContent=C().map;document.getElementById('reviewTitle').textContent=C().review;document.querySelector('.problem-nav>span').textContent=C().problems;document.querySelector('.back').textContent=REVIEW_LANG==='zh'?'复盘档案':'Review archive';document.querySelectorAll('#scoreEditor label').forEach((x,i)=>x.childNodes[0].textContent=[C().correct,C().wrong,C().blank][i]);document.querySelectorAll('footer a')[0].textContent=REVIEW_LANG==='zh'?'全部复盘记录':'All review records';document.querySelectorAll('footer a')[1].textContent=REVIEW_LANG==='zh'?'数学路线图':'Math roadmap';document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('on',b.dataset.lang===REVIEW_LANG));const total=EXAM.problems.reduce((a,p)=>a+stageCount(ps(p.number)),0);document.getElementById('progressText').textContent=`${total}/${EXAM.problems.length*3} ${C().progress}`;const correct=Number(document.getElementById('editCorrect')?.value??SCORE_STATE.correct??ATTEMPT.correct??0),wrong=Number(document.getElementById('editWrong')?.value??SCORE_STATE.wrong??ATTEMPT.wrong??0),blank=Number(document.getElementById('editBlank')?.value??SCORE_STATE.blank??ATTEMPT.blank??0),score=correct*6+blank*1.5;document.getElementById('examScore').textContent=`${score.toFixed(1)} / 150`;document.getElementById('scoreFacts').innerHTML=`<div><dt>${C().correct}</dt><dd>${correct}</dd></div><div><dt>${C().wrong}</dt><dd>${wrong}</dd></div><div><dt>${C().blank}</dt><dd>${blank}</dd></div>`;const sum=correct+wrong+blank;document.getElementById('scoreEditor').classList.toggle('invalid',sum!==25);document.getElementById('editScore').textContent=sum===25?`${score.toFixed(1)} ${REVIEW_LANG==='zh'?'分':'points'}`:`${REVIEW_LANG==='zh'?'总数应为25，目前':'Total must be 25; currently'} ${sum}`;}
function renderNav(){document.getElementById('problemNav').innerHTML=EXAM.problems.map(p=>{const s=ps(p.number),done=stageCount(s);return `<a href="#problem-${p.number}" class="stage-${done}" aria-label="Problem ${p.number}, ${done} of 3 stages">${p.number}<i>${done}/3</i></a>`}).join('')}
function renderMap(){document.getElementById('problemMap').innerHTML=`<table class="map-table"><thead><tr><th>#</th><th>${REVIEW_LANG==='zh'?'题型':'Family'}</th><th>${REVIEW_LANG==='zh'?'第一表示':'First representation'}</th><th>${REVIEW_LANG==='zh'?'状态':'Status'}</th></tr></thead><tbody>${EXAM.problems.map(p=>{const s=ps(p.number);return `<tr><td>${p.number}</td><td>${esc(L(p.topic))}</td><td>${esc(s.map?representations.find(r=>r[0]===s.map.representation)?.[REVIEW_LANG==='zh'?2:1]||s.map.representation:L(p.mapSummary))}</td><td><span class="mini-progress"><i style="--done:${stageCount(s)}"></i>${stageCount(s)}/3</span></td></tr>`}).join('')}</tbody></table>`}
function renderStatusRail(s){const status=(done,ready)=>done?C().passed:ready?C().ready:C().locked;return `<ol class="status-rail"><li class="${s.reviewedAt?'done':'active'}"><i>1</i><div><b>${C().reviewed}</b><span>${C().stageReview}</span></div><em>${status(s.reviewedAt,true)}</em></li><li class="${s.transferPassedAt?'done':s.reviewedAt?'active':''}"><i>2</i><div><b>${C().transfer}</b><span>${C().stageTransfer}</span></div><em>${status(s.transferPassedAt,s.reviewedAt)}</em></li><li class="${s.coldPassedAt?'done':coldReady(s)?'active':''}"><i>3</i><div><b>${C().cold}</b><span>${C().stageCold}</span></div><em>${s.coldPassedAt?C().passed:coldReady(s)?C().ready:s.transferPassedAt?C().locked:C().locked}</em></li></ol>`}
function renderProblem(p){const s=ps(p.number),open=s.outcome||s.map||s.reviewedAt;return `<details class="problem" id="problem-${p.number}" ${open?'open':''}><summary><span class="qno">${p.number}</span><span><b class="problem-title">${esc(L(p.title)||L(p.topic))}</b><span class="problem-topic">${esc(L(p.topic))}</span></span><span class="problem-state">${stageCount(s)}/3 · ${summaryLabel(s)}</span></summary><div class="problem-body">${renderStatusRail(s)}<section class="attempt-panel"><div class="attempt-top"><p class="eyebrow">${C().timer}</p><strong class="timer" data-timer="${p.number}:main">${formatTime(timerValue(s,'main'))}</strong></div><div class="stem">${esc(L(p.stem))}</div><div class="options">${p.options.map(o=>`<label class="option"><input type="radio" name="answer-${p.number}" value="${esc(o.key)}" ${s.answer===o.key?'checked':''} ${s.outcome?'disabled':''}><b>${o.key}</b><span>${esc(o.text)}</span></label>`).join('')}</div>${renderAttemptActions(p,s)}</section>${s.outcome?renderMapping(p,s):''}${s.map?renderHelp(p,s):''}${s.reviewedAt?renderTransfer(p,s):''}${s.transferPassedAt?renderCold(p,s):''}</div></details>`}
function renderAttemptActions(p,s){if(s.outcome)return `<div class="attempt-result ${s.outcome}"><b>${outcomeLabel(s)}</b><span>${C().before}: ${esc(s.answer||'—')} · ${C().timer} ${formatTime(timerValue(s,'main'))}</span></div>`;return `<div class="attempt-actions"><button class="primary" data-action="submit-answer" data-n="${p.number}">${C().submitAnswer}</button><button data-action="blank" data-n="${p.number}">${C().markBlank}</button><button class="text-button" data-action="giveup" data-n="${p.number}">${C().giveUp}</button></div><p class="feedback" role="alert" aria-live="assertive" data-feedback="attempt-${p.number}"></p>`}

function renderMapping(p,s){const selected=s.map?.concepts||[];return `<section class="mapping ${s.map?'complete':''}"><p class="eyebrow">01 · ${C().mapFirst}</p><h3>${esc(L(p.prompt))}</h3><p>${C().mapHelp}</p><div class="concepts">${p.concepts.map(c=>`<button type="button" class="concept ${selected.includes(c.id)?'selected':''}" data-action="concept" data-n="${p.number}" data-concept="${c.id}" aria-pressed="${selected.includes(c.id)}">${esc(L(c.label))}</button>`).join('')}</div><label class="field"><span>${C().representation}</span><select data-map-representation="${p.number}"><option value="">—</option>${representations.map(r=>`<option value="${r[0]}" ${s.map?.representation===r[0]?'selected':''}>${esc(r[REVIEW_LANG==='zh'?2:1])}</option>`).join('')}</select></label><label class="field"><span>${C().reason}</span><textarea data-map-reason="${p.number}" rows="3" placeholder="${esc(C().whyMap)}">${esc(s.map?.reason||'')}</textarea></label>${s.map?`<p class="success-note">✓ ${C().mapSaved}</p>`:''}<button class="primary" data-action="save-map" data-n="${p.number}">${s.map?(REVIEW_LANG==='zh'?'更新映射':'Update map'):C().saveMap}</button><p class="feedback" aria-live="polite" data-feedback="map-${p.number}"></p></section>`}
function renderHelp(p,s){const shown=Math.min(s.hintsOpened,p.hints.length);return `<section class="coaching"><p class="eyebrow">02 · ${REVIEW_LANG==='zh'?'分层提示':'Layered coaching'}</p>${p.hints.map((h,i)=>`<article class="hint-card ${i<shown?'open':''} ${i===shown?'next':''}"><header><span>${C().hint} ${i+1}</span>${L(h.prompt)?`<b>${esc(L(h.prompt))}</b>`:''}</header>${i<shown?`<p>${esc(L(h.content))}</p>`:i===shown&&!s.reviewedAt?`<button data-action="open-hint" data-n="${p.number}">${C().hint} ${i+1}</button>`:'<span class="lock-mark">—</span>'}</article>`).join('')}<div class="solution-gate"><p>${s.hintsOpened?C().tryAgain:C().tryAgain}</p>${s.reviewedAt?renderSolutions(p,s):`<button class="primary" data-action="open-solution" data-n="${p.number}">${C().openSolution}</button>`}</div></section>`}
function renderSolutions(p,s){return `<section class="solution"><p class="eyebrow">03 · ${C().solution}</p>${p.solutions.length>1?`<div class="method-tabs">${p.solutions.map((m,i)=>`<button data-action="method" data-n="${p.number}" data-method="${i}" class="${i===0?'on':''}">${i+1}. ${esc(L(m.title))}</button>`).join('')}</div>`:''}<div class="method-body" data-method-body="${p.number}">${solutionBody(p.solutions[0])}</div></section>`}
function solutionBody(m){return `<h3>${esc(L(m.title))}</h3><ol>${m.steps.map(x=>`<li>${esc(L(x))}</li>`).join('')}</ol>${m.insight?`<blockquote>${esc(L(m.insight))}</blockquote>`:''}<p class="solution-result"><span>${C().answerLabel}</span><b>${esc(m.result)}</b></p>`}
function renderTransfer(p,s){const item=p.practice[Math.min(s.transferIndex,p.practice.length-1)]||p.practice[0],revealed=s.transferPassedAt;return `<section class="transfer-stage ${s.transferPassedAt?'passed':''}"><p class="eyebrow">04 · ${C().practice}</p><h3>${C().independent}</h3><article class="transfer-card"><span class="level">${esc(item.level||'Transfer 01')}</span><p>${esc(L(item.question))}</p><label class="field compact"><span>${C().answerLabel}</span><input data-transfer-answer="${p.number}" ${revealed?'disabled':''}></label>${revealed?`<p class="success-note">✓ ${C().passed} · ${C().answerAfterPass} <b>${esc(L(item.answer))}</b></p>`:`<button class="primary" data-action="check-transfer" data-n="${p.number}">${C().check}</button><p class="feedback" aria-live="polite" data-feedback="transfer-${p.number}"></p>`}</article></section>`}
function renderCold(p,s){if(s.coldPassedAt)return `<section class="cold-stage passed"><p class="eyebrow">05 · ${C().cold}</p><p class="success-note">✓ ${C().passed} · ${formatTime(s.coldElapsed)}</p></section>`;if(!coldReady(s)){const left=48*60*60*1000-(Date.now()-s.transferPassedAt),hours=Math.ceil(left/3600000);return `<section class="cold-stage locked"><p class="eyebrow">05 · ${C().cold}</p><h3>${C().wait48}</h3><p>${hours} ${REVIEW_LANG==='zh'?'小时后开放':'hours remaining'}</p></section>`}return `<section class="cold-stage"><p class="eyebrow">05 · ${C().cold}</p><h3>${C().coldRule}</h3><div class="attempt-top"><span>${C().timer}</span><strong class="timer" data-timer="${p.number}:cold">${formatTime(timerValue(s,'cold'))}</strong></div>${s.coldStartedAt?`<div class="stem">${esc(L(p.stem))}</div><div class="options">${p.options.map(o=>`<label class="option"><input type="radio" name="cold-${p.number}" value="${esc(o.key)}"><b>${o.key}</b><span>${esc(o.text)}</span></label>`).join('')}</div><button class="primary" data-action="submit-cold" data-n="${p.number}">${C().coldSubmit}</button><p class="feedback" role="alert" aria-live="assertive" data-feedback="cold-${p.number}"></p>`:`<button class="primary" data-action="start-cold" data-n="${p.number}">${C().coldStart}</button>`}</section>`}

function render(){Object.values(timers).forEach(clearInterval);timers={};renderHeader();renderNav();renderMap();document.getElementById('problems').innerHTML=EXAM.problems.map(renderProblem).join('');EXAM.problems.forEach(p=>{const s=ps(p.number);if(!s.outcome&&document.querySelector(`#problem-${p.number}[open]`))startTimer(p.number);if(s.coldStartedAt&&!s.coldPassedAt)startTimer(p.number,'cold')});renderMath()}
function feedback(key,msg,good=false){const el=document.querySelector(`[data-feedback="${key}"]`);if(el){el.textContent=msg;el.classList.toggle('good',good)}}
function answerForAction(n,name){return document.querySelector(`input[name="${name}-${n}"]:checked`)?.value||''}
function handleAction(btn){const n=Number(btn.dataset.n),p=EXAM.problems.find(x=>x.number===n),s=ps(n),action=btn.dataset.action;if(action==='submit-answer'){const a=answerForAction(n,'answer');if(!a){feedback(`attempt-${n}`,REVIEW_LANG==='zh'?'请先选择一个答案；如果决定不作答，请点“留空”。':'Choose an answer first, or use Leave blank if that is your decision.');return}setOutcome(n,'answer',a)}if(action==='blank')setOutcome(n,'blank');if(action==='giveup')setOutcome(n,'giveup');if(action==='concept'){btn.classList.toggle('selected');btn.setAttribute('aria-pressed',btn.classList.contains('selected'));return}if(action==='save-map'){const concepts=[...document.querySelectorAll(`[data-action="concept"][data-n="${n}"].selected`)].map(x=>x.dataset.concept),representation=document.querySelector(`[data-map-representation="${n}"]`).value,reason=document.querySelector(`[data-map-reason="${n}"]`).value.trim();const relevant=!p.required.length||concepts.filter(x=>p.required.includes(x)).length>=2;if(concepts.length<2||!representation||reason.length<12){feedback(`map-${n}`,C().mapNeed);return}if(!relevant){feedback(`map-${n}`,REVIEW_LANG==='zh'?'至少两个所选知识点必须是本题的核心知识点。':'At least two selected concepts must be central to this problem.');return}s.map={concepts,representation,reason,savedAt:Date.now()};save();render()}if(action==='open-hint'){s.hintsOpened=Math.min(p.hints.length,s.hintsOpened+1);s.hintUsed=true;save();render()}if(action==='open-solution'){s.reviewedAt=Date.now();save();render()}if(action==='method'){document.querySelectorAll(`[data-action="method"][data-n="${n}"]`).forEach(x=>x.classList.toggle('on',x===btn));document.querySelector(`[data-method-body="${n}"]`).innerHTML=solutionBody(p.solutions[Number(btn.dataset.method)]);renderMath(document.querySelector(`[data-method-body="${n}"]`));return}if(action==='check-transfer'){const item=p.practice[Math.min(s.transferIndex,p.practice.length-1)]||p.practice[0],input=document.querySelector(`[data-transfer-answer="${n}"]`).value;if([L(item.answer),item.answer?.en,item.answer?.zh].filter(Boolean).some(x=>{const a=normalize(input),b=normalize(x);return a===b||b.startsWith(a+';')||b.startsWith(a+'。')||b.startsWith(a+'hours')||b.startsWith(a+'pairs')})){s.transferPassedAt=Date.now();save();render()}else{s.transferAttempts++;save();feedback(`transfer-${n}`,REVIEW_LANG==='zh'?'还不对。检查单位、条件和最终问法后再试；答案不会提前显示。':'Not yet. Check units, constraints, and what the problem asks for, then retry; the answer stays hidden.')}}if(action==='start-cold'){s.coldStartedAt=Date.now();s.coldElapsed=0;save();render()}if(action==='submit-cold'){const input=answerForAction(n,'cold');if(!input){feedback(`cold-${n}`,REVIEW_LANG==="zh"?"请先选择一个答案。":"Choose an answer before submitting the cold redo.");return}if(isCorrect(input,p)){s.coldElapsed+=Date.now()-s.coldStartedAt;s.coldStartedAt=null;s.coldAnswer=input;s.coldPassedAt=Date.now();save();render()}else{feedback(`cold-${n}`,C().statusWrong)}}}
document.addEventListener('click',e=>{const btn=e.target.closest('[data-action]');if(btn)handleAction(btn);const lang=e.target.closest('[data-lang]');if(lang){REVIEW_LANG=lang.dataset.lang;localStorage.setItem('am_lang',REVIEW_LANG);location.reload()}});
document.addEventListener('toggle',e=>{if(!e.target.matches?.('.problem'))return;const n=Number(e.target.id.replace('problem-','')),s=ps(n);if(e.target.open&&!s.outcome)startTimer(n);else if(!e.target.open&&s.startedAt){s.elapsed+=Date.now()-s.startedAt;s.startedAt=null;save();stopTimer(n)}},true);
document.querySelectorAll('#scoreEditor input').forEach((input,i)=>{const key=['correct','wrong','blank'][i];input.value=SCORE_STATE[key]??ATTEMPT[key]??0;input.addEventListener('input',()=>{SCORE_STATE[key]=Number(input.value);localStorage.setItem(SCORE_KEY,JSON.stringify(SCORE_STATE));renderHeader()})});
document.getElementById('scoreEditor').addEventListener('submit',e=>e.preventDefault());
document.querySelector('.recheck').innerHTML=`<h2>${REVIEW_LANG==='zh'?'真正掌握的判定':'What “mastered” means'}</h2><ol><li><b>1 · ${C().reviewed}</b><span>${C().stageReview}</span></li><li><b>2 · ${C().transfer}</b><span>${C().stageTransfer}</span></li><li><b>3 · ${C().cold}</b><span>${C().stageCold}</span></li></ol>`;
render();

